//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_cycleOccur_base.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef PROJECT_MACRAT_DLG_CYCLEOCCUR_BASE_BASE_CLASSES_H
#define PROJECT_MACRAT_DLG_CYCLEOCCUR_BASE_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class DlgCycleOccurBase : public wxDialog
{
protected:
    wxPanel* m_panel4;
    wxStaticText* m_staticText10;
    wxTextCtrl* m_textCtrlFilename;
    wxButton* m_buttonBrowse;
    wxStdDialogButtonSizer* m_stdBtnSizer18;
    wxButton* m_buttonOk;
    wxButton* m_buttonCancel;

protected:
    virtual void OnButtonBrowse(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText10() { return m_staticText10; }
    wxTextCtrl* GetTextCtrlFilename() { return m_textCtrlFilename; }
    wxButton* GetButtonBrowse() { return m_buttonBrowse; }
    wxPanel* GetPanel4() { return m_panel4; }
    DlgCycleOccurBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Process Cycle Occur"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgCycleOccurBase();
};

#endif
