//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_select_folder.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "dlg_select_folder.h"


// Declare the bitmap loading function
extern void wxCEF84InitBitmapResources();

static bool bBitmapLoaded = false;


DlgSelectFolderBase::DlgSelectFolderBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCEF84InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer19 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer19);
    
    m_panel29 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer19->Add(m_panel29, 0, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer31 = new wxBoxSizer(wxVERTICAL);
    m_panel29->SetSizer(boxSizer31);
    
    m_panel85 = new wxPanel(m_panel29, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer31->Add(m_panel85, 0, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer87 = new wxBoxSizer(wxHORIZONTAL);
    m_panel85->SetSizer(boxSizer87);
    
    m_staticText33 = new wxStaticText(m_panel85, wxID_ANY, _("Folder"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer87->Add(m_staticText33, 0, wxALL, 5);
    
    m_textCtrlFolder = new wxTextCtrl(m_panel85, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(350,-1), wxTE_READONLY);
    #if wxVERSION_NUMBER >= 3000
    m_textCtrlFolder->SetHint(wxT(""));
    #endif
    
    boxSizer87->Add(m_textCtrlFolder, 1, wxALL, 5);
    
    m_buttonSelFolder = new wxButton(m_panel85, wxID_ANY, _("Select Folder"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer87->Add(m_buttonSelFolder, 0, wxALL|wxEXPAND|wxALIGN_RIGHT, 5);
    
    m_panel39 = new wxPanel(m_panel29, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer31->Add(m_panel39, 0, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer41 = new wxBoxSizer(wxHORIZONTAL);
    m_panel39->SetSizer(boxSizer41);
    
    m_staticText43 = new wxStaticText(m_panel39, wxID_ANY, _("Smooth width"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer41->Add(m_staticText43, 0, wxALL, 5);
    
    m_textCtrlSmooth = new wxTextCtrl(m_panel39, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), 0);
    #if wxVERSION_NUMBER >= 3000
    m_textCtrlSmooth->SetHint(wxT(""));
    #endif
    
    boxSizer41->Add(m_textCtrlSmooth, 0, wxALL, 5);
    
    m_checkBoxSymbol = new wxCheckBox(m_panel39, wxID_ANY, _("Symbols on peaks"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_checkBoxSymbol->SetValue(false);
    
    boxSizer41->Add(m_checkBoxSymbol, 0, wxALL, 5);
    
    m_stdBtnSizer75 = new wxStdDialogButtonSizer();
    
    boxSizer31->Add(m_stdBtnSizer75, 0, wxALL|wxEXPAND, 5);
    
    m_button77 = new wxButton(m_panel29, wxID_OK, wxT(""), wxDefaultPosition, wxSize(-1, -1), 0);
    m_stdBtnSizer75->AddButton(m_button77);
    
    m_button79 = new wxButton(m_panel29, wxID_CANCEL, wxT(""), wxDefaultPosition, wxSize(-1, -1), 0);
    m_stdBtnSizer75->AddButton(m_button79);
    m_stdBtnSizer75->Realize();
    
    SetName(wxT("DlgSelectFolderBase"));
    SetSizeHints(-1,-1);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    m_buttonSelFolder->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgSelectFolderBase::OnButtonSelectFolder), NULL, this);
    
}

DlgSelectFolderBase::~DlgSelectFolderBase()
{
    m_buttonSelFolder->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgSelectFolderBase::OnButtonSelectFolder), NULL, this);
    
}
