//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_select_folder.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef MACRAT_DLG_SELECT_FOLDER_BASE_CLASSES_H
#define MACRAT_DLG_SELECT_FOLDER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class DlgSelectFolderBase : public wxDialog
{
protected:
    wxPanel* m_panel4;
    wxStdDialogButtonSizer* m_stdBtnSizer6;
    wxButton* m_button10;
    wxButton* m_button12;

protected:

public:
    wxPanel* GetPanel4() { return m_panel4; }
    DlgSelectFolderBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Select folder"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgSelectFolderBase();
};

#endif
