//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_cycleOccur_base.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "dlg_cycleOccur_base.h"


// Declare the bitmap loading function
extern void wxCrafterc30dvrInitBitmapResources();

static bool bBitmapLoaded = false;


DlgCycleOccurBase::DlgCycleOccurBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterc30dvrInitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer2 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer2);
    
    m_panel4 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer2->Add(m_panel4, 0, wxALL, 5);
    
    wxBoxSizer* boxSizer6 = new wxBoxSizer(wxVERTICAL);
    m_panel4->SetSizer(boxSizer6);
    
    m_panel33 = new wxPanel(m_panel4, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer6->Add(m_panel33, 0, wxALL, 5);
    
    wxBoxSizer* boxSizer8 = new wxBoxSizer(wxHORIZONTAL);
    m_panel33->SetSizer(boxSizer8);
    
    m_staticText10 = new wxStaticText(m_panel33, wxID_ANY, _("File"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer8->Add(m_staticText10, 0, wxALL, 5);
    
    m_textCtrlFilename = new wxTextCtrl(m_panel33, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), 0);
    #if wxVERSION_NUMBER >= 3000
    m_textCtrlFilename->SetHint(wxT(""));
    #endif
    
    boxSizer8->Add(m_textCtrlFilename, 0, wxALL, 5);
    m_textCtrlFilename->SetMinSize(wxSize(350,-1));
    
    m_buttonBrowse = new wxButton(m_panel33, wxID_ANY, _("Browse"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer8->Add(m_buttonBrowse, 0, wxALL, 5);
    
    m_panel35 = new wxPanel(m_panel4, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer6->Add(m_panel35, 0, wxALL, 5);
    
    wxStaticBoxSizer* staticBoxSizer29 = new wxStaticBoxSizer( new wxStaticBox(m_panel35, wxID_ANY, _("Group by")), wxHORIZONTAL);
    m_panel35->SetSizer(staticBoxSizer29);
    
    m_buttonGroupAmpIntvl = new wxButton(m_panel35, wxID_ANY, _("amp and intvl"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    staticBoxSizer29->Add(m_buttonGroupAmpIntvl, 0, wxALL, 5);
    
    m_buttonGroupSound = new wxButton(m_panel35, wxID_ANY, _("sound (dB)"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    staticBoxSizer29->Add(m_buttonGroupSound, 0, wxALL, 5);
    
    m_buttonGroupIncDec = new wxButton(m_panel35, wxID_ANY, _("Inc and Dec"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    staticBoxSizer29->Add(m_buttonGroupIncDec, 0, wxALL, 5);
    
    m_stdBtnSizer18 = new wxStdDialogButtonSizer();
    
    boxSizer6->Add(m_stdBtnSizer18, 0, wxALL|wxALIGN_RIGHT, 5);
    
    m_buttonOk = new wxButton(m_panel4, wxID_OK, wxT(""), wxDefaultPosition, wxSize(-1, -1), 0);
    m_stdBtnSizer18->AddButton(m_buttonOk);
    
    m_buttonCancel = new wxButton(m_panel4, wxID_CANCEL, wxT(""), wxDefaultPosition, wxSize(-1, -1), 0);
    m_stdBtnSizer18->AddButton(m_buttonCancel);
    m_stdBtnSizer18->Realize();
    
    SetName(wxT("DlgCycleOccurBase"));
    SetSize(500,400);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    m_buttonBrowse->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnButtonBrowse), NULL, this);
    m_buttonGroupAmpIntvl->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnGroupAmpIntvl), NULL, this);
    m_buttonGroupSound->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnGroupSound), NULL, this);
    m_buttonGroupIncDec->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnGroupIncDec), NULL, this);
    
}

DlgCycleOccurBase::~DlgCycleOccurBase()
{
    m_buttonBrowse->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnButtonBrowse), NULL, this);
    m_buttonGroupAmpIntvl->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnGroupAmpIntvl), NULL, this);
    m_buttonGroupSound->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnGroupSound), NULL, this);
    m_buttonGroupIncDec->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(DlgCycleOccurBase::OnGroupIncDec), NULL, this);
    
}
