//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_optical_input_base.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef DLG_OPTICAL_INPUT_BASE_BASE_CLASSES_H
#define DLG_OPTICAL_INPUT_BASE_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/statbox.h>
#include <wx/checkbox.h>
#include <wx/textctrl.h>
#include <wx/stattext.h>
#include <wx/radiobut.h>
#include <wx/statline.h>
#include <wx/gbsizer.h>
#include <wx/button.h>

class DlgOpticalInputBase : public wxDialog
{
protected:
    wxPanel* m_panel163;
    wxCheckBox* m_checkBoxLED;
    wxCheckBox* m_checkBoxVerLine;
    wxTextCtrl* m_textCtrlVerLine;
    wxCheckBox* m_checkBoxEyeMove;
    wxCheckBox* m_checkBoxEar;
    wxCheckBox* m_checkBoxBelly;
    wxCheckBox* m_checkBoxBigHead;
    wxCheckBox* m_checkBoxLED2;
    wxTextCtrl* m_textCtrlLED2;
    wxPanel* m_panel171;
    wxCheckBox* m_checkBoxOpticalPDF;
    wxCheckBox* m_checkBoxGrayDiff;
    wxCheckBox* m_checkBoxSaveFlow;
    wxStaticText* m_staticText181;
    wxRadioButton* m_radioOpV1;
    wxRadioButton* m_radioOpV2;
    wxStaticLine* m_staticLine781;
    wxPanel* m_panel38;
    wxStaticText* m_staticText718;
    wxTextCtrl* m_textCtrlFrameSteps;
    wxStaticText* m_staticText1320;
    wxStaticText* m_staticText1923;
    wxTextCtrl* m_textCtrlThreshold;
    wxStaticText* m_staticText132;
    wxTextCtrl* m_textCtrlHeadGain;
    wxStaticText* m_staticText136;
    wxTextCtrl* m_textCtrlBellyGain;
    wxStaticLine* m_staticLine78;
    wxPanel* m_panel187;
    wxStaticText* m_staticText100;
    wxTextCtrl* m_textCtrlYmin;
    wxStaticText* m_staticText104;
    wxTextCtrl* m_textCtrlYmax;
    wxStaticText* m_staticText124;
    wxTextCtrl* m_textCtrlROIEar;
    wxStaticText* m_staticText1241;
    wxTextCtrl* m_textCtrlROIAPB;
    wxStaticText* m_staticText203;
    wxRadioButton* m_radioButtonRefBelly;
    wxRadioButton* m_radioButtonRefHead;
    wxRadioButton* m_radioButtonRefEar;
    wxPanel* m_panel116;
    wxStaticText* m_staticText126;
    wxTextCtrl* m_textCtrlReferFrame;
    wxStaticText* m_staticText130;
    wxStaticLine* m_staticLine108;
    wxStdDialogButtonSizer* m_stdBtnSizer52;
    wxButton* m_button56;
    wxButton* m_button58;

protected:

public:
    DlgOpticalInputBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Optical Input Dialog"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgOpticalInputBase();
};

#endif
