//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_optical_input_base.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef DLG_OPTICAL_INPUT_BASE_BASE_CLASSES_H
#define DLG_OPTICAL_INPUT_BASE_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>

class DlgOpticalInputBase : public wxDialog
{
protected:
    wxPanel* m_panel516;
    wxStaticText* m_staticText718;
    wxTextCtrl* m_textCtrlFrameSteps;
    wxStaticText* m_staticText1320;
    wxPanel* m_panel1521;
    wxStaticText* m_staticText1923;
    wxTextCtrl* m_textCtrlThreshold;
    wxPanel* m_panel2325;
    wxButton* m_buttonOk;
    wxButton* m_buttonCancel;

protected:

public:
    DlgOpticalInputBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Optical Input Dialog"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(400,200), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgOpticalInputBase();
};

#endif
