//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_process_next.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef PROJECT_MACRAT_DLG_PROCESS_NEXT_BASE_CLASSES_H
#define PROJECT_MACRAT_DLG_PROCESS_NEXT_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class DlgProcessNextBase : public wxDialog
{
protected:
    wxStaticText* m_staticText8;
    wxTextCtrl* m_textCtrlAmpLow;
    wxTextCtrl* m_textCtrlAmpUp;
    wxTextCtrl* m_textCtrlAmpSnd;
    wxStaticText* m_staticText16;
    wxTextCtrl* m_textCtrlIntervalLow;
    wxTextCtrl* m_textCtrlIntervalUp;
    wxTextCtrl* m_textCtrlIntervalSnd;
    wxButton* m_buttonReplot;
    wxButton* m_buttonNext;
    wxButton* m_buttonBreak;

protected:
    virtual void OnReplot(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText8() { return m_staticText8; }
    wxTextCtrl* GetTextCtrlAmpLow() { return m_textCtrlAmpLow; }
    wxTextCtrl* GetTextCtrlAmpUp() { return m_textCtrlAmpUp; }
    wxTextCtrl* GetTextCtrlAmpSnd() { return m_textCtrlAmpSnd; }
    wxStaticText* GetStaticText16() { return m_staticText16; }
    wxTextCtrl* GetTextCtrlIntervalLow() { return m_textCtrlIntervalLow; }
    wxTextCtrl* GetTextCtrlIntervalUp() { return m_textCtrlIntervalUp; }
    wxTextCtrl* GetTextCtrlIntervalSnd() { return m_textCtrlIntervalSnd; }
    wxButton* GetButtonReplot() { return m_buttonReplot; }
    wxButton* GetButtonNext() { return m_buttonNext; }
    wxButton* GetButtonBreak() { return m_buttonBreak; }
    DlgProcessNextBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Process next ..."), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgProcessNextBase();
};

#endif
