//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: optical.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef OPTICAL_BASE_CLASSES_H
#define OPTICAL_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>

class DlgOpticalBase : public wxDialog
{
protected:
    wxStaticText* m_staticText4;
    wxTextCtrl* m_textCtrl_PYR_LAYERS;
    wxStaticText* m_staticText8;
    wxTextCtrl* m_textCtrl_WIN_SIZE;
    wxStaticText* m_staticText12;
    wxTextCtrl* m_textCtrl_ITER;
    wxStaticText* m_staticText16;
    wxTextCtrl* m_textCtrl_NEIGHBOR;
    wxStaticText* m_staticText20;
    wxTextCtrl* m_textCtrl_SIGMA;
    wxStaticText* m_staticText24;
    wxTextCtrl* m_textCtrl_FRAME_STEPS;
    wxButton* m_buttonOK;
    wxButton* m_buttonCANCEL;

protected:

public:
    DlgOpticalBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Optical Flow Dialog"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgOpticalBase();
};

#endif
